import Head from 'next/head';
import Link from 'next/link';
import { BsExclamation, BsExclamationCircle, BsStarFill } from 'react-icons/bs';



export default function readMore() {


  return (
  
    <>
    <Head>
    <title>Make your dreams come true from Start to Star | Greixed Consult</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/greixed logo (4).png"/>
    </Head>
    <main className={styles.container}>
        <div className={styles.body}>
        <h1 className={styles.heading}>
        From Start to Star
        <BsStarFill color='gold'/>
        <BsStarFill color='gold'/>
        <BsStarFill color='gold'/>
     </h1>
     <div className={styles.text}>
        <p>
            {/* Here,we will make mention of one of the tips in making your abroad study happen */}
            Do you have the dream of travelling abroad through schorlaships??
            well then, you are in the right place.
            we help you scale through the process and procedures of gaining one.
            IELTS,TOFEFL are one of the basic requirements needed to school abroad.
            some people do ask why is it so??
            the answer to that, it is because the use of english for every country is needed
            as it will qualify you for the schorlaship as a participant.
            Securing schorlaships in different countries of the world, has lots of processes to be followed.
            There are classification of schorlaships to be applied;
           
        </p>
    </div>
        <div className={styles.text}>
          
        <li>
                the undergraduate application
              </li>
              
              <li>
                As an exchange student
              </li>
              
              <li>
                Bsc OR Masters degree application and many more
              </li>
              <h1 className={styles.header}>The Undergraduate Application</h1>
              <p>
                This application goes for the ones who are under
                18 years and their parents or guardian has a working job in that desired country.
                This is made so beacuse, one of the ethics for a child under 18years to travel out
                is that he/she must have a guardian who will be able to travel out with him/her.
                A child is also expected to be matured before gaining a schorlaship or visa to travel out.
              </p>
              <h1 className={styles.header}>An Exchange Student</h1>
              <p>
              This application goes for the ones who are already at university and wants to be transfered
              to another school in Canada for example,at 200 level. He or she has to get an aproval letter from the
              school he/she attends to be able to process this to complete this schorlaship procedure.
              </p>
              <h1 className={styles.header}> Bsc OR Masters degree application</h1>
              <p>
                There are schorlaships mainly for those who after they have graduated from the university attended,
                wants to futher their education by applying for a masters degree or doctorate degree programme.
                he/she are needed to meet up with the academic expections about him/her from the
                school and therefore apply.
              </p>
              <p className={styles.header}>
                <u>
                  NOTE;
                </u>
              </p>
              <p>
                Anyone who desires to gain a schorlaship can gain one.
                No matter the exams given to you, with your desire,motivation,strong-will,reading and studying,
                you can do it !!!
              </p>
              <p className={styles.texts}>To apply for the obtainable valid schorlaship application, click the link Below</p>
        </div>
        <div className={styles.linkButton}>
          <Link className={styles.link}  href='https://wa.me/+2347019860086'>Apply Now</Link>
      </div>
        </div>
    </main>
    </>
       
  )}

  const styles ={
    container:'lg:px-0 sm:px-5',
    heading:'text-3xl text-blue-600 font-bold mt-5 px-3 flex flex-row gap-3',
    text:'mt-5 px-3 text-2xl leading-relaxed text-black justify-end',
    texts:'mt-10 text-yellow-500  text-2xl text-black text-center',
    linkButton:'flex justify-center py-5',
    header:'mt-5 text-yellow-400',
    link:'h-[40px] w-[400px] mt-5 bg-blue-800 hover:bg-yellow-500 lg:px-3 rounded-lg text-center text-2xl text-white',
  }