
import { useState,useEffect } from 'react';
import Head from 'next/head';



export default function termsAndConditions() {
 

 

  return (
  
    <>
    <Head>
    <title>terms and conditions apply | Greixed Consult</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/greixed logo (4).png"/>
    </Head>
    <main className={styles.container}>
     
  
    </main>
    </>
       
  )}

  const styles={
    container:'h-screen',
  }