
import Head from 'next/head';



export default function termsAndConditions() {
 

 

  return (
  
    <>
    <Head>
    <title>terms and conditions apply | Greixed Consult</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/greixed logo (4).png"/>
    </Head>
    <main className={styles.container}>
     <div className={styles.body}>
      <p>Greixed Consult is made to provide adequate learning programs to every student who wants to learn, pass
        exams and get schorlaships which are valid
      </p>
     </div>
  
    </main>
    </>
       
  )}

  const styles={
    container:'',
    body:'text-1xl justify-end',
  }